# Generated by Django 4.1.7 on 2023-03-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='regNum',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
