# Generated by Django 4.1.7 on 2023-03-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_participant_email_alter_participant_regnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='year',
        ),
    ]
