# Generated by Django 4.1.7 on 2023-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_participant_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
