# Generated by Django 4.1.7 on 2023-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_participant_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
