# Generated by Django 4.1.7 on 2023-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_participant_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='year',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
